### ISSUE TITLE
frescobaldi build fails due to poppler-qt4 no longer existing

### ISSUE THREAD

**Issue by cartr** [cartr/homebrew-qt4#22]
I suspect the solution is to package our own `poppler` with the Qt 4 backend -- not sure how doable this is (has Poppler retired their Qt 4 support?)

**Comment by albertosottile** [comment]
Are you still interested in a PR for this? I just tested it locally, everything works besides homebrew/lilypond that has been deprecated and moved to a cask (the user can still install it manually if needed).

**Comment by cartr** [comment]
I'd definitely still be interested in a PR for this if you've gotten it
working.

**Comment by albertosottile** [comment]
That's great, I have a question though: at this moment I had to create poppler formula using the same name as in homebrew-core because the poppler path is hardcoded somewhere in the frescobaldi building code. If that is ok for you, I can quickly prepare the PR. Otherwise, I'll change the name to something like poppler-qt4 and try to fix it in the frescobaldi formula or with a patch.

**Comment by cartr** [comment]
It'd probably be better to use a new name, like poppler-qt4, so people
could install it and homebrew-core's Poppler side-by-side if they wanted to.

**Comment by albertosottile** [comment]
Ok, working on it. 
**EDIT**: Nevermind, it works. Opening the PR now.

**Comment by cartr** [comment]
Fixed by #61.
