### ISSUE TITLE
qmake -query returns incorrect path

### ISSUE THREAD

**Issue by bblacey** [cartr/homebrew-qt4#25]
This discrepancy causes cmake generation to fail because certain Qt cmake variables are not correctly defined by find_program(qt4).  Note `QT_INSTALL_PLUGINS` and `QT_INSTALL_IMPORTS` point to nonexistent `qt4` directories but should be correct for a keg-only install.

```
$ qmake -query
QT_INSTALL_PREFIX:/usr/local
QT_INSTALL_DATA:/usr/local/Cellar/qt@4/4.8.7
QT_INSTALL_DOCS:/usr/local/doc
QT_INSTALL_HEADERS:/usr/local/include
QT_INSTALL_LIBS:/usr/local/lib
QT_INSTALL_BINS:/usr/local/bin
QT_INSTALL_PLUGINS:/usr/local/lib/qt4/plugins
QT_INSTALL_IMPORTS:/usr/local/lib/qt4/imports
QT_INSTALL_TRANSLATIONS:/usr/local/Cellar/qt@4/4.8.7/translations
QT_INSTALL_CONFIGURATION:/usr/local
QT_INSTALL_EXAMPLES:/usr/local/Cellar/qt@4/4.8.7/examples
QT_INSTALL_DEMOS:/usr/local/Cellar/qt@4/4.8.7/demos
QMAKE_MKSPECS:/usr/local/Cellar/qt@4/4.8.7/mkspecs
QMAKE_VERSION:2.01a
QT_VERSION:4.8.7
```

I haven't identified a root cause yet but reporting in case it is obvious to someone more familiar with these Qt4 formulae.

**Comment by cartr** [comment]
I patch configure to point most of the paths to `/usr/local/`, which should have all the Qt 4 files symlinked into them. This is necessary to allow qmake and cmake to find WebKit, since WebKit isn't installed in the same Cellar folder as Qt any more.

Is the only issue that `_PLUGINS`, `_IMPORTS`, `_DATA`, and `_TRANSLATIONS` should be changed?

**Comment by cartr** [comment]
Also, do you have a public project/CMakeLists.txt file I could use to reproduce the issue? [The file I was using to test stuff](https://gist.github.com/cartr/1ad0c7473cc37d1e98579eef25e0111f) `cmake`s and builds fine on my machine.

**Comment by bblacey** [comment]
The problem seems to be with hardwired paths in the [Qt4 formula](https://github.com/cartr/homebrew-qt4/blob/master/qt%404.rb#L110-L111).

**Comment by cartr** [comment]
@bblacey Sorry, I'm not clear on which of the paths are currently wrong. All of them? Just the `/usr/local/Cellar/` paths? Or all the paths except for the `/usr/local/Cellar/` paths?

**Comment by bblacey** [comment]
Right now, the configure patching sets some of the paths to non-existant paths.  At a minimum, they should point to valid paths that exist but ideally paths that work for keg-only installs.  The two obvious paths are:
```
QT_INSTALL_PLUGINS:/usr/local/lib/qt4/plugins
QT_INSTALL_IMPORTS:/usr/local/lib/qt4/imports
```
Plugins should be `/usr/local/Cellar/qt@4/4.8.7/plugins` or `/usr/local/opt/qt@4/plugins` and imports should be `/usr/local/Cellar/qt@4/4.8.7/imports` or `/usr/local/opt/qt@4/translations`.

**Comment by bblacey** [comment]
@cartr - what happens if you don't patch those two paths?  Will configure set them properly?

**Comment by bblacey** [comment]
@cartr - I also noticed that configure allows you to specify these paths as arguments to configure that seems a bit cleaner than using `inreplace`.  You can see these options using `./configure --help`.

```
 You may use these to separate different parts of the install:

    -bindir <dir> ......... Executables will be installed to <dir>
                            (default PREFIX/bin)
    -libdir <dir> ......... Libraries will be installed to <dir>
                            (default PREFIX/lib)
    -docdir <dir> ......... Documentation will be installed to <dir>
                            (default PREFIX/doc)
    -headerdir <dir> ...... Headers will be installed to <dir>
                            (default PREFIX/include)
    -plugindir <dir> ...... Plugins will be installed to <dir>
                            (default PREFIX/plugins)
    -importdir <dir> ...... Imports for QML will be installed to <dir>
                            (default PREFIX/imports)
    -datadir <dir> ........ Data used by Qt programs will be installed to <dir>
                            (default PREFIX)
    -translationdir <dir> . Translations of Qt programs will be installed to <dir>
                            (default PREFIX/translations)
    -sysconfdir <dir> ..... Settings used by Qt programs will be looked for in <dir>
                            (default PREFIX/etc/settings)
    -examplesdir <dir> .... Examples will be installed to <dir>
                            (default PREFIX/examples)
    -demosdir <dir> ....... Demos will be installed to <dir>
                            (default PREFIX/demos)
```

**Comment by cartr** [comment]
@bblacey If we don't patch these paths, the `./configure` script will set them to `/usr/local/Cellar/qt@4/4.8.7/[plugins, imports, bin, etc.]`. For most of the paths, this is incorrect and we need to change them to `/usr/local/[bin, lib, etc.]` -- otherwise, build scripts won't find WebKit. But I think you're right that the Plugins and Imports paths are set incorrectly. In your opinion, would it be better to set them to `/usr/local/Cellar/qt@4/4.8.7/[plugins, imports]` or `/usr/local/opt/qt@4/[plugins, imports]`?

Also, the issue with using those `./configure` flags is that the path we want Qt to install to (`/usr/local/Cellar/qt@4/4.8.7/`) and the path we want it to claim it's installed to when someone asks (`/usr/local/`) are different. So we need to patch `./configure` to make qmake report the second path while being installed to the first.

**Comment by bblacey** [comment]
@cartr - either will work but given that the other paths point to the formula's `prefix` (i.e. `/usr/local/Cellar/qt@4/4.8.7`), I would probably use the same prefix for the plugins and translations.

**Comment by bblacey** [comment]
I "think" that if just remove the `inreplace` for those two paths, I think they might be set to the cellar prefix.

**Comment by cartr** [comment]
@bblacey I just submitted a Pull Request that fixes this by going the other way: rather than removing the `inreplace` commands to change the path reported by `qmake`, it updates the configure arguments to install the plugins and imports in the places `qmake` currently reports.

I think this solution will be a bit better because it ensures that build scripts receive the same paths even when `qt@4`'s version number changes. It also encourages people to install their plugins into /usr/local/lib/qt4 rather than `qt@4`'s Cellar path which is changed every time the formula updates.
