### ISSUE TITLE
Bottles for high_sierra

### ISSUE THREAD

**Issue by scpeters** [cartr/homebrew-qt4#36]
I imagine you will create high_sierra bottles for `qt@4` and other formulae at some point. Let me know if you need any help with this.

**Comment by cartr** [comment]
Thanks for the offer! I'll likely have bottles for `qt@4`, `qt-webkit@4`, PySide, and PyQt on High Sierra ready this weekend.

Just so people know, the Qt 4 package should still work on High Sierra without the bottles – it'll just take longer to install because it needs to compile everything from scratch. If you're running into problems using Qt 4 on High Sierra, please [file an issue](https://github.com/cartr/homebrew-qt4/issues/new) so we can get them resolved.
