### ISSUE TITLE
Travis-CI times out while attempting to install qt

### ISSUE THREAD

**Issue by tresf** [cartr/homebrew-qt4#7]
Attempting to leverage `cartr/qt4/qt` on a continuous-integration build system the below error occurs:

Direct link to build failure:  https://travis-ci.org/LMMS/lmms/jobs/188301347#L630

Downstream script logic:  https://github.com/LMMS/lmms/pull/3201/files

```diff
  ==> Installing qt from cartr/qt4
  ==> Downloading https://download.qt.io/official_releases/qt/4.8/4.8.7/qt-everywh
  ==> Downloading from http://qt.mirrors.tds.net/qt/official_releases/qt/4.8/4.8.7
  ==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/480b7
  ==> Downloading https://raw.githubusercontent.com/cartr/homebrew-qt4/41669527a2a
  ==> Patching
  ==> Applying el-capitan.patch
  patching file src/gui/painting/qpaintengine_mac.cpp
  ==> Applying qsetting-nulls.patch
  patching file src/corelib/io/qsettings.cpp
  patching file src/corelib/io/qsettings_mac.cpp
- patch unexpectedly ends in middle of line
- Hunk #2 succeeded at 276 with fuzz 1.
  ==> ./configure -prefix /usr/local/Cellar/qt/4.8.7_3 -release -opensource -confi
  ==> make
  No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
  Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
  The build has been terminated
```

**Comment by cartr** [comment]
That patch warning likely isn't the root problem; it happens on any machine that builds the formula from source and doesn't seem to cause issues there.

According to [their docs](https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version), Travis uses El Capitan by default. Since I don't currently provide binary builds for El Capitan, it's trying to build Qt4 from source and timing out. The easiest way to fix this on your end would be to set `osx_image: xcode8.2` to switch to Sierra, for which a binary is available.

**Comment by tresf** [comment]
@cartr Thanks for the detailed explanation.  I was just reading up on stalled builds and Travis offers a [20-minute tickler](https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received) as well, but your solution will ensure the build occurs quicker, which is a win-win.  Thanks!

Closing as this is not an issue with `cartr/qt4/qt`.
